executor: go-machine-large
steps:
  - setup-go
  - checkout
  - go_test:
      extra_flags: "-p 1 -race"
      log_dir: "/tmp/testlogs"
  - store_artifacts:
      path: test-results
  - store_test_results:
      path: test-results
  - store_artifacts:
      path: "/tmp/testlogs"
